# Generated by Django 3.1.4 on 2022-01-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
