# Generated by Django 3.2.4 on 2021-08-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_video_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='speaker',
            field=models.CharField(default='', max_length=100),
        ),
    ]
