# Generated by Django 4.0.2 on 2022-02-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20220201_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
