# Generated by Django 3.1.4 on 2022-01-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20220122_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=350)),
                ('phone', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
    ]
