# Generated by Django 3.1.4 on 2022-01-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20220129_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='unique_name',
            field=models.CharField(default='Enter A Unique Name', max_length=250),
            preserve_default=False,
        ),
    ]
